export interface District {
  id: number
  name: string
}

export interface City {
  id: number
  name: string
  districts: District[]
}

export const turkeyCities: City[] = [
  {
    id: 1,
    name: "Adana",
    districts: [
      { id: 1, name: "Aladağ" },
      { id: 2, name: "Ceyhan" },
      { id: 3, name: "Çukurova" },
      { id: 4, name: "Feke" },
      { id: 5, name: "İmamoğlu" },
      { id: 6, name: "Karaisalı" },
      { id: 7, name: "Karataş" },
      { id: 8, name: "Kozan" },
      { id: 9, name: "Pozantı" },
      { id: 10, name: "Saimbeyli" },
      { id: 11, name: "Sarıçam" },
      { id: 12, name: "Seyhan" },
      { id: 13, name: "Tufanbeyli" },
      { id: 14, name: "Yumurtalık" },
      { id: 15, name: "Yüreğir" },
    ],
  },
  {
    id: 2,
    name: "Adıyaman",
    districts: [
      { id: 16, name: "Besni" },
      { id: 17, name: "Çelikhan" },
      { id: 18, name: "Gerger" },
      { id: 19, name: "Gölbaşı" },
      { id: 20, name: "Kahta" },
      { id: 21, name: "Merkez" },
      { id: 22, name: "Samsat" },
      { id: 23, name: "Sincik" },
      { id: 24, name: "Tut" },
    ],
  },
  {
    id: 3,
    name: "Afyonkarahisar",
    districts: [
      { id: 25, name: "Başmakçı" },
      { id: 26, name: "Bayat" },
      { id: 27, name: "Bolvadin" },
      { id: 28, name: "Çay" },
      { id: 29, name: "Çobanlar" },
      { id: 30, name: "Dazkırı" },
      { id: 31, name: "Dinar" },
      { id: 32, name: "Emirdağ" },
      { id: 33, name: "Evciler" },
      { id: 34, name: "Hocalar" },
      { id: 35, name: "İhsaniye" },
      { id: 36, name: "İscehisar" },
      { id: 37, name: "Kızılören" },
      { id: 38, name: "Merkez" },
      { id: 39, name: "Sandıklı" },
      { id: 40, name: "Sinanpaşa" },
      { id: 41, name: "Sultandağı" },
      { id: 42, name: "Şuhut" },
    ],
  },
  {
    id: 6,
    name: "Ankara",
    districts: [
      { id: 43, name: "Akyurt" },
      { id: 44, name: "Altındağ" },
      { id: 45, name: "Ayaş" },
      { id: 46, name: "Bala" },
      { id: 47, name: "Beypazarı" },
      { id: 48, name: "Çamlıdere" },
      { id: 49, name: "Çankaya" },
      { id: 50, name: "Çubuk" },
      { id: 51, name: "Elmadağ" },
      { id: 52, name: "Etimesgut" },
      { id: 53, name: "Evren" },
      { id: 54, name: "Gölbaşı" },
      { id: 55, name: "Güdül" },
      { id: 56, name: "Haymana" },
      { id: 57, name: "Kalecik" },
      { id: 58, name: "Kazan" },
      { id: 59, name: "Keçiören" },
      { id: 60, name: "Kızılcahamam" },
      { id: 61, name: "Mamak" },
      { id: 62, name: "Nallıhan" },
      { id: 63, name: "Polatlı" },
      { id: 64, name: "Pursaklar" },
      { id: 65, name: "Sincan" },
      { id: 66, name: "Şereflikoçhisar" },
      { id: 67, name: "Yenimahalle" },
    ],
  },
  {
    id: 7,
    name: "Antalya",
    districts: [
      { id: 68, name: "Akseki" },
      { id: 69, name: "Aksu" },
      { id: 70, name: "Alanya" },
      { id: 71, name: "Demre" },
      { id: 72, name: "Döşemealtı" },
      { id: 73, name: "Elmalı" },
      { id: 74, name: "Finike" },
      { id: 75, name: "Gazipaşa" },
      { id: 76, name: "Gündoğmuş" },
      { id: 77, name: "İbradı" },
      { id: 78, name: "Kaş" },
      { id: 79, name: "Kemer" },
      { id: 80, name: "Kepez" },
      { id: 81, name: "Konyaaltı" },
      { id: 82, name: "Korkuteli" },
      { id: 83, name: "Kumluca" },
      { id: 84, name: "Manavgat" },
      { id: 85, name: "Muratpaşa" },
      { id: 86, name: "Serik" },
    ],
  },
  {
    id: 34,
    name: "İstanbul",
    districts: [
      { id: 87, name: "Adalar" },
      { id: 88, name: "Arnavutköy" },
      { id: 89, name: "Ataşehir" },
      { id: 90, name: "Avcılar" },
      { id: 91, name: "Bağcılar" },
      { id: 92, name: "Bahçelievler" },
      { id: 93, name: "Bakırköy" },
      { id: 94, name: "Başakşehir" },
      { id: 95, name: "Bayrampaşa" },
      { id: 96, name: "Beşiktaş" },
      { id: 97, name: "Beykoz" },
      { id: 98, name: "Beylikdüzü" },
      { id: 99, name: "Beyoğlu" },
      { id: 100, name: "Büyükçekmece" },
      { id: 101, name: "Çatalca" },
      { id: 102, name: "Çekmeköy" },
      { id: 103, name: "Esenler" },
      { id: 104, name: "Esenyurt" },
      { id: 105, name: "Eyüpsultan" },
      { id: 106, name: "Fatih" },
      { id: 107, name: "Gaziosmanpaşa" },
      { id: 108, name: "Güngören" },
      { id: 109, name: "Kadıköy" },
      { id: 110, name: "Kağıthane" },
      { id: 111, name: "Kartal" },
      { id: 112, name: "Küçükçekmece" },
      { id: 113, name: "Maltepe" },
      { id: 114, name: "Pendik" },
      { id: 115, name: "Sancaktepe" },
      { id: 116, name: "Sarıyer" },
      { id: 117, name: "Silivri" },
      { id: 118, name: "Sultanbeyli" },
      { id: 119, name: "Sultangazi" },
      { id: 120, name: "Şile" },
      { id: 121, name: "Şişli" },
      { id: 122, name: "Tuzla" },
      { id: 123, name: "Ümraniye" },
      { id: 124, name: "Üsküdar" },
      { id: 125, name: "Zeytinburnu" },
    ],
  },
  {
    id: 35,
    name: "İzmir",
    districts: [
      { id: 126, name: "Aliağa" },
      { id: 127, name: "Balçova" },
      { id: 128, name: "Bayındır" },
      { id: 129, name: "Bayraklı" },
      { id: 130, name: "Bergama" },
      { id: 131, name: "Beydağ" },
      { id: 132, name: "Bornova" },
      { id: 133, name: "Buca" },
      { id: 134, name: "Çeşme" },
      { id: 135, name: "Çiğli" },
      { id: 136, name: "Dikili" },
      { id: 137, name: "Foça" },
      { id: 138, name: "Gaziemir" },
      { id: 139, name: "Güzelbahçe" },
      { id: 140, name: "Karabağlar" },
      { id: 141, name: "Karaburun" },
      { id: 142, name: "Karşıyaka" },
      { id: 143, name: "Kemalpaşa" },
      { id: 144, name: "Kınık" },
      { id: 145, name: "Kiraz" },
      { id: 146, name: "Konak" },
      { id: 147, name: "Menderes" },
      { id: 148, name: "Menemen" },
      { id: 149, name: "Narlıdere" },
      { id: 150, name: "Ödemiş" },
      { id: 151, name: "Seferihisar" },
      { id: 152, name: "Selçuk" },
      { id: 153, name: "Tire" },
      { id: 154, name: "Torbalı" },
      { id: 155, name: "Urla" },
    ],
  },
  // Diğer iller de eklenebilir, şimdilik en çok kullanılan illeri ekledim
]

export function getCityById(cityId: number): City | undefined {
  return turkeyCities.find((city) => city.id === cityId)
}

export function getDistrictsByCity(cityId: number): District[] {
  const city = getCityById(cityId)
  return city ? city.districts : []
}
